# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tools/advancedDebugger/mainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(792, 558)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 80, 421, 471))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.groupBox.setObjectName("groupBox")
        self.serialSendButton = QtWidgets.QPushButton(self.groupBox)
        self.serialSendButton.setGeometry(QtCore.QRect(320, 440, 89, 25))
        self.serialSendButton.setObjectName("serialSendButton")
        self.serialLogOutput = QtWidgets.QTextEdit(self.groupBox)
        self.serialLogOutput.setGeometry(QtCore.QRect(0, 20, 421, 411))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.serialLogOutput.setFont(font)
        self.serialLogOutput.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.serialLogOutput.setReadOnly(True)
        self.serialLogOutput.setObjectName("serialLogOutput")
        self.serialLogInput = QtWidgets.QLineEdit(self.groupBox)
        self.serialLogInput.setGeometry(QtCore.QRect(10, 440, 291, 25))
        self.serialLogInput.setObjectName("serialLogInput")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 0, 781, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.comPortSelect = QtWidgets.QComboBox(self.groupBox_2)
        self.comPortSelect.setGeometry(QtCore.QRect(90, 34, 581, 25))
        self.comPortSelect.setObjectName("comPortSelect")
        self.connectButton = QtWidgets.QPushButton(self.groupBox_2)
        self.connectButton.setGeometry(QtCore.QRect(680, 34, 89, 25))
        self.connectButton.setObjectName("connectButton")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 37, 91, 17))
        self.label.setObjectName("label")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(440, 80, 341, 471))
        self.groupBox_3.setObjectName("groupBox_3")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_3)
        self.tabWidget.setGeometry(QtCore.QRect(0, 20, 341, 451))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_General = QtWidgets.QWidget()
        self.tab_General.setObjectName("tab_General")
        self.tabWidget.addTab(self.tab_General, "")
        self.tab_CPU = QtWidgets.QWidget()
        self.tab_CPU.setObjectName("tab_CPU")
        self.tabWidget.addTab(self.tab_CPU, "")
        self.tab_Disk = QtWidgets.QWidget()
        self.tab_Disk.setObjectName("tab_Disk")
        self.tabWidget.addTab(self.tab_Disk, "")
        self.tab_Memory = QtWidgets.QWidget()
        self.tab_Memory.setObjectName("tab_Memory")
        self.tabWidget.addTab(self.tab_Memory, "")
        self.tab_Processes = QtWidgets.QWidget()
        self.tab_Processes.setObjectName("tab_Processes")
        self.tabWidget.addTab(self.tab_Processes, "")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "CactusOS Debugger"))
        self.groupBox.setTitle(_translate("mainWindow", "Serial Log:"))
        self.serialSendButton.setText(_translate("mainWindow", "Send"))
        self.groupBox_2.setTitle(_translate("mainWindow", "Serial Settings"))
        self.connectButton.setText(_translate("mainWindow", "Connect"))
        self.label.setText(_translate("mainWindow", "COM Port:"))
        self.groupBox_3.setTitle(_translate("mainWindow", "Stats:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_General), _translate("mainWindow", "General"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_CPU), _translate("mainWindow", "CPU"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Disk), _translate("mainWindow", "Disk"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Memory), _translate("mainWindow", "Memory"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Processes), _translate("mainWindow", "Processes"))
